# Generated by Django 3.0.8 on 2020-07-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CowrieAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('success', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('url', models.TextField()),
                ('outfile', models.TextField(blank=True, null=True)),
                ('shasum', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'downloads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('realm', models.CharField(blank=True, max_length=50, null=True)),
                ('success', models.IntegerField(blank=True, null=True)),
                ('input', models.TextField()),
            ],
            options={
                'db_table': 'input',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipforwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('dst_ip', models.CharField(max_length=255)),
                ('dst_port', models.IntegerField()),
            ],
            options={
                'db_table': 'ipforwards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipforwardsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('dst_ip', models.CharField(max_length=255)),
                ('dst_port', models.IntegerField()),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'ipforwardsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyfingerprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'keyfingerprints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('arch', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'params',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sensors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.IntegerField()),
                ('ip', models.CharField(max_length=15)),
                ('termsize', models.CharField(blank=True, max_length=7, null=True)),
                ('client', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ttylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('ttylog', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'ttylog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IP_enrichment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_anonymous', models.BooleanField()),
                ('is_known_attacker', models.BooleanField()),
                ('is_known_abuser', models.BooleanField()),
                ('is_threat', models.BooleanField()),
            ],
            options={
                'verbose_name': 'enrichment',
                'db_table': 'ip_enrichments',
            },
        ),
    ]
