# Generated by Django 3.0.8 on 2020-07-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IP_enrichment',
            new_name='Ipenrichments',
        ),
    ]
